### ISSUE TITLE
Fix and refactor user-workouts component to reactive decalarative

### ISSUE THREAD

**Issue by MikhailRatner** [johannesstroebele91/FoxyFit#38]
- [x] Refactor user-workouts component to reactive declarative, so if the dialog is closed, the new user observable gets emitted

**Comment by johannesstroebele91** [comment]
@MikhailRatner ich hab den Issue etwas angepasst und die Änderungen direkt gepushed. Dann können wir davon auch bei anderen Sachen weiterarbeiten (wollte mir mal das responsive Thema anschauen und Co). Funktioniert ja, außer dass es nicht gere-rendered wird.

**Comment by MikhailRatner** [comment]
user$ ist nun reactive declarative. Leider hat es nicht dazu geführt dass das Highliting funktioniert. Da müssen wir wohl nochmal ein manuelles re-rendering ausführen.
